name: app

type: golang:1.10

hooks:
    build: |
        set -e
        curl -o /tmp/rust.sh https://sh.rustup.rs
        chmod +x /tmp/rust.sh
        /tmp/rust.sh -y
        /app/.cargo/bin/cargo build --release
        mv target/release/rust-example .
        rm -rf target

web:
    upstream:
        socket_family: tcp
        protocol: http

    commands:
        start: |
            ROCKET_ENV=prod ROCKET_PORT=$PORT ./rust-example

    locations:
        /:
            root: www
            allow: false
            passthru: true

disk: 1024
