name: app

type: golang:1.10

# std::web is broken in the current nightly.
# of course, neither this framework nor the webass part will compile on stable or beta...
hooks:
    build: |
        set -e
        curl -o /tmp/rust.sh https://sh.rustup.rs
        chmod +x /tmp/rust.sh
        /tmp/rust.sh -y --default-toolchain nightly
        . ~/.cargo/env
        rustup target add wasm32-unknown-unknown
        cargo install cargo-web
        cargo build --release -p backend
#        cargo web build --release -p frontend --target wasm32-unknown-unknown
        mv target/release/backend .
        rm -rf src
        rm -rf target

web:
    upstream:
        socket_family: tcp
        protocol: http

    commands:
        start: |
            ROCKET_ENV=prod ROCKET_PORT=$PORT ./rust-example

    locations:
        /:
            allow: false
            passthru: true
        /static:
            root: static
            allow: false
            passthru: true

disk: 1024
