[package]
name = "rust-example"
version = "0.1.0"
authors = ["Royall Spence <royall@royall.us>"]

[workspace]
members = ["backend", "frontend"]

[[bin]]
name = "backend"
path = "backend/src/main.rs"

[[bin]]
name = "frontend"
path = "frontend/src/main.rs"
