[package]
name = "backend"
version = "0.1.0"
authors = ["Royall Spence <royall@royall.us>"]

[dependencies]
rocket = "0.3"
rocket_codegen = "0.3"
serde = "1.0"
serde_derive = "1.0"
tera = "0.11"

[dependencies.rocket_contrib]
version = "0.3"
default-features = false
features = ["tera_templates"]
